default:
  APPLICATION_URL_REGISTRATION: $APPLICATION_URL/gccorp/registration
  APPLICATION_URL_ADDRESS: $APPLICATION_URL/gccorp/address
  APPLICATION_URL_RELATIONSHIP: $APPLICATION_URL/gccorp/relationship
  TEMPLATE_PATH: ../templates
  TOB_API_URL: http://tob-api:8080/api/v2
  TOB_APP_URL: http://localhost:8080
  INDY_WALLET_SEED: gccorp.von.canada.ca_dev_0000000
